name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.86.0
      with:
        components: clippy, rustfmt 
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}    
    - run: cargo fmt --all -- --check
    - run: cargo clippy --all-targets --all-features -- -D warnings      
    - run: cargo build --verbose
    - run: cargo test --verbose
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2025-04-28
        components: rustfmt      
    - run: cargo +nightly-2025-04-28 fmt --all -- --check
